import express from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { generateTrackFromPrompt, renderTrackToWavBase64 } from './proceduralEngine';
const app = express();
const PORT = process.env.PORT || 10000;
app.use(helmet());
app.use(cors());
app.use(bodyParser.json({ limit: '5mb' }));
app.use(rateLimit({ windowMs: 60*1000, max: Number(process.env.RATE_LIMIT || 120) }));
app.get('/api/presets', (req,res)=>{ res.json({ ok:true, presets: ['zamba','african voices','brazil drums','mexican trumpet','house','lofi','ambient'] }); });
app.post('/api/generate', async (req,res)=>{ try{ const { prompt, bpm=100, key='C', mode='minor' } = req.body || {}; if(!prompt) return res.status(400).json({ error:'prompt required' }); const track = generateTrackFromPrompt({ channelId:'ch1', prompt, bpm, key, mode }); const wavBase64 = await renderTrackToWavBase64(track, { sampleRate:44100 }); res.json({ status:'ok', prompt, bpm, key, track, audioStream: 'data:audio/wav;base64,' + wavBase64 }); }catch(e:any){ console.error(e); res.status(500).json({ error:'server error', detail: e.message }); } });
app.listen(PORT, ()=> console.log('Soundeus backend (Deus) running on', PORT));
